blog/urls.py
from django.urls import path
from . import views
from .views import PostDeleteConfirm, PostDelete, PostDeleteSuccess

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('favorites/', views.favorite_list, name='favorite_list'),
    path('profile/', views.profile_view, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('not_logged_in/', views.not_logged_in, name='not_logged_in'),
    path('post/create/', views.PostCreate.as_view(), name='post_create'),
    path('post/<int:pk>/edit/', views.PostEdit.as_view(), name='post_edit'),
    path('post/<int:pk>/delete/', PostDeleteConfirm.as_view(),
         name='post_delete_confirm'),
    path('post/<int:pk>/delete/confirm', PostDelete.as_view(),
         name='post_delete'),
    path('post/delete/success', PostDeleteSuccess.as_view(),
         name='post_delete_success'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path('<slug:slug>/edit_comment/<int:comment_id>',
         views.comment_edit, name='comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>',
         views.comment_delete, name='comment_delete'),
    path('<slug:slug>/approve_comment/<int:comment_id>/',
         views.approve_comment, name='approve_comment'),
    path('like_post/<int:post_id>/', views.like_post, name='like_post'),
    path('unlike_post/<int:post_id>/', views.unlike_post, name='unlike_post'),
    path('category/all/', views.PostList.as_view(),
         name='post_list_by_category_all'),
    path('category/<str:category>/', views.post_list_by_category,
         name='post_list_by_category'),
    path('favorite_post/<int:post_id>/', views.favorite_post,
         name='favorite_post'),
    path('unfavorite_post/<int:post_id>/', views.unfavorite_post,
         name='unfavorite_post'),
]

hwblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("about/", include("about.urls"), name="about-urls"),
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
]

templates/base.html
{% load static %}

{% url 'home' as home_url %}
{% url 'about' as about_url %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}

<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    <title>HW|Blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Meta tags for search engines --> 
    <meta name="description" content="HWBlog - Your Source for Hardware, Coding, and 3D Printing Insights"> 
    <meta name="keywords" content="Explore the latest trends, tutorials, and reviews in the world of hardware, coding, and 3D printing on HWBlog. Get expert insights and stay updated with our informative articles."> 

    <!-- Favicon--> 
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}"> 
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}"> 
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">

    <!-- Google Fonts CSS -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body data-user-authenticated="{% if user.is_authenticated %}true{% else %}false{% endif %}" class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'blog:home' %}"><span class="brand">HW<span class="redsep">|</span>Blog</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == home_url %}active" aria-current="page{% endif %}"
                            href="{% url 'blog:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == about_url %}active" aria-current="page{% endif %}"
                            href="{% url 'about' %}">About</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:favorite_list' %}">Favorites</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:profile' %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                        </li>
                        {% if user.is_staff or user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="/admin/">ADMIN</a>
                        </li>
                        {% endif %}
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:not_logged_in' %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
                <span class="navbar-text text-muted">
                    your favorite blog
                </span>
            </div>
        </div>
    </nav>
     <!-- displaying Django messages -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <main class="flex-shrink-0 main-bg">
        {% if user.is_authenticated %}
            <p class="text-end m-3">You are logged in as <a href="{% url 'blog:profile' %}">{{ user.username }}</a></p>
        {% else %}
            <p class="text-end m-3">You are not logged in. <a href="{% url 'account_login' %}">Log in here</a></p>
        {% endif %}

        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}

    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center text-white">
            {% block copyright %}Copyright &#169; 2024 Georgios Kopanidis<br>
            for educational purposes only
            {% endblock copyright %}
          </p>
        <p class="m-0 text-center text-white">
            Follow us: 
            <a href="https://www.facebook.com/" class="text-white no-underline" target="_blank" rel="noopener" aria-label="Visit our Facebook page (opens in a new tab)">
                <i class="fab fa-facebook-square ms-3"></i>
            </a>
            <a href="https://www.twitter.com/" class="text-white no-underline" target="_blank" rel="noopener" aria-label="Visit our Twitter profile (opens in a new tab)">
                <i class="fab fa-twitter-square ms-3"></i>
            </a>
            <a href="https://www.instagram.com/" class="text-white no-underline" target="_blank" rel="noopener" aria-label="Visit our Instagram profile (opens in a new tab)">
                <i class="fab fa-instagram-square ms-3"></i>
            </a>
            <a href="https://www.youtube.com/" class="text-white no-underline" target="_blank" rel="noopener" aria-label="Visit our YouTube channel (opens in a new tab)">
                <i class="fab fa-youtube-square ms-3"></i>
            </a>
            <a href="https://github.com/GKopanidis" class="text-white no-underline" target="_blank" rel="noopener" aria-label="Visit our GitHub profile (opens in a new tab)">
                <i class="fab fa-github-square ms-3"></i>
            </a>
            <a href="https://www.linkedin.com/in/georgios-k-308588267/" class="text-white no-underline" target="_blank" rel="noopener" aria-label="Visit our LinkedIn profile (opens in a new tab)">
                <i class="fab fa-linkedin ms-3"></i>
            </a>
        </p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
        </script>
    {% block extras %}
    {% endblock %}
</html>